#pragma prefix "utexas.edu"

///
module CCVSM {
	/**
	* Data information: dimension of the dataset
	*/	
	struct DataInfo {
		long dim[3];
	};

	/**
	* The eye position, viewing direction and up vector
	*/
	struct ViewParam {
		long  perspective;      // Perspective 1 or Orthogonal 0
		float fov;              // Field of View
		float pos[3];           // Camera position 		
		float vec[3];           // View plane normal
		float up[3];            // View up vector 
	};

	/**
	* The volume rendered image from server
	*/ 
	struct Image {
		long dx;
		long dy;
		long res;
		sequence<char> img; 
	};
	
	/**
	* The list of available files
	*/
	typedef sequence<string> FileList;

	typedef long RampInfo[3];

	/**
	* The dimension of viewing volume
	*/
	typedef long ViewField[3];

	/**
	* Material information
	*/
	struct MatInfo {
		float opacity;              /* Opacity value */
 
		long start;                /* Each denotes a point where the direction  */
		long up;                   /* of the material graph changes             */
		long down;
		long end;
 
		long kar, kag, kab;        /* Ambient Color. (r,g,b) */
		long kdr, kdg, kdb;        /* Diffuse Color. (r,g,b) */
		long ksr, ksg, ksb;        /* Specular Color. (r,g,b) */
		long kn;                   /* Exponent */
	};

	/**
	* Lighting information
	*/
	struct LightInfo {
		long red, green, blue;		/* Light color (r, g, b) */
		float vx, vy, vz;			/* Light direction (vx, vy, vz) */
	};
	

	/**
	 * Isocontour information
	 * @param cflag: 0 -- use the RGB color to color surface;
	 *               i > 0 -- use the ith function to color surface
	 */
	struct ContourInfo {
		float val;                   /* isovalue */
		long ar, ag, ab;             /* ambient color */
		long dr, dg, db;             /* diffuse color */
		long sr, sg, sb;             /* specular color */
		float opacity;               /* opacity */
		long cflag;                  
	};

	/**
	*  The size of volume rendering image
	*/
	typedef long WinSize[2];

	/**
	* One slice of volume data
	*/
	struct Slice {
		long dx;
		long dy;
		sequence<float> data;
		};

	/**
	* Data load exception
	*/
	exception DataLoadException {
		string reason;
		};

	/**
	* Direction of sampling slice
	*/ 
	enum Direction {TOP, BOTTOM, FRONT, BACK, RIGHT, LEFT};

	/**
	* Volume rendering sampling method
	*/
	enum SampleMethod {NEAREST, TRI_INTERP};

	/**
	*  rgb and alpha value of a density point.
	*/ 
	struct DenMaterial {
		long den;
		long r, g, b, alpha;
	};

	/**
	 * up to 4096 density points in the definition of transfer function.
	 */
	typedef sequence<DenMaterial, 4096> DenTransfer;

	/**
	 * Current state of the parallel rendering server
	 */
	struct ServerState {
		long n_mat;
		long n_con;
		long n_light;
	};

	/**
	 * Parameters for a subvolume
	 */
	struct SubVolume {
		float ox, oy, oz;       // coordinates of the origin
		float dx, dy, dz;       // spans of the subvolume
	};



// Added by smpark -----------------------------------------------------

    // Quaternion Matrix for rotation
	struct SRotationMatrix {
		float  RotMat[4][4];
	};


    // Transfer Function Node structure
    struct STFNNode {
        long  Density;
		long  R, G, B, A;
    };

	typedef sequence<STFNNode, 1024> SeqSTFNNodes;

//june added-----------------------------------------------------------
	// Get the compressed image with processNum and image size
	struct CompImagesWithSize {
	 	long mv_FrontToBack;
		long NumOfProcess;
		long mv_recvImageSize[1][7];
		sequence<char> mv_CompImage;
	};
	
// The end of adding ---------------------------------------------------



	/**
	 * Parallel volume rendering server.
	 * It listens to client request and uses multiple slave processes 
	 * to raytrace a volume parallelly.
	 *
	 */
	interface PVolServerSM {
	    /**@name methods */
	    //@{

// Added by smpark -----------------------------------------------------

        // Start New File
//		void setNew();

        /// Send File Number
		void setFileNumber(in long FileNum);
		
		/// Set TimeStep
		void setTimeStep(in long TimeStep);

        /// Send 4x4 Rotation Matrix(Quaternion)
		void setRotationMatrix(in SRotationMatrix RotMat);
		
		/// Send the Transfer function nodes
		void setTransferFunctionNodes(in SeqSTFNNodes Nodes);
		//void setDenTransfer(in DenTransfer dtrans);

		void FlipNormals(in long Flip);

		void setViewFrustum(in float scale, in float clip, in float MoveX, in float MoveY);
		
		// Get Rendered Image pieces and composite them
		Image getRenderedImage();

		
		// Send exit signal to server
		void TerminateServer();
		

//june added ---------------------------------------------------------	

		/// get a display tile flag
		long getDisplayFlag(in long tileNum);
		
		/// Get the number of Process,compressed image size,
		/// and compressed image
		CompImagesWithSize getCompImages(in long tileNum);  
 
 		/// set the EnlargeX, EnlargeY, EnlargeZ 
//		void setEnlarge(in float enlargeX,in float enlargeY,in float enlargeZ); 
		
		/// set the location of object
//		void setLocation(in float x, in float y);

		/// reset the displayflag
		void resetDisplayFlag(in long tileNum);
					
//-------------------------------------------------------------------
		
		
// The end of adding ---------------------------------------------------

		/**
		 * load a volume data file
		 */
		boolean loadData(in string filename)
			/*, in float x, in float y, in float z)*/ raises(DataLoadException);

		/**
		* get information about volume data
		*/
		DataInfo getDataInfo();

		/**
		 * quit and destroy the servant
		 */
		void quit();

		/**
		 * set viewing parameters
		 */
		void setViewParam(in ViewParam param);

		/**
		 * most important function of FCastServer
		 * It distributes tiles to slave processes to compute and 
		 * return the final image to client
		 * client should call this function in seperate thread such that
		 * user may cancel the rendering operation
		 */
		Image render();

		/**
		 * cancel the current rendering operation
		 * @note not implemented
		 */
		void cancel();

		/**
		 * return the number of slave hosts used in the rendering
		 */
		 long getNumOfHosts();

		/**
		 * get a slice
		 * @param dir direct direction of the slice
		 * @param n the slice number along dir
		 * @note not implemented in hun's library
		 */
		Slice getSlice(in Direction dir, in long n);

		/**
		 * set sampling method
		 */
		 void setSamplingMethod(in SampleMethod method);

		/**
		 * set field of view
		 */
		 void setViewField(in ViewField vf);

		/**
		 * return list of config files
		 */
		 FileList getConfigFiles();

		 /**
		  * retrieve the number of materials, contours and lights
		  */
		 ServerState getServerState();

		/**
		 * set and get material information
		 * @param n The nth material type (up to the current num of materials)
		 * 
		 */
		 void setMaterial(in MatInfo mat, in long n);
		 MatInfo getMaterial(in long n);

		 /**
		  * Add a new material type
		  */
		 void addMaterial(in MatInfo mat);

		/**
		 * set and get Light information
		 * @param n The nth light (up to the current number of lights)
		 */
		 void setLight(in LightInfo light, in long n);
		 LightInfo getLight(in long n);

		 /**
		  * Add a new light
		  */
		 void addLight(in LightInfo light);

		/**
		 * set image size
		 */
		void setImageSize(in WinSize win);
		
		/**
		 * set the viewing window size.
		 */
		void setWindowSize(in WinSize win);
		/**
		 * get the viewing window size
		 */	
		WinSize getWindowSize();		

		/**
		 * get the nth contour information.
		 */
		ContourInfo getContourInfo(in long n);

		/**
		 * set the nth contour information.
		 */
		void setContourInfo(in ContourInfo con, in long n);

		/**
		 * Add a new contour.
		 */
		void addContour(in ContourInfo con);

		/**
		 * Set Rendering mode.
		 * @param mode 
		 *  2: Vol ren with material shapes
		 *  3: Vol ren with material shapes + isocontouring
		 *  4: Vol ren with density transfer function
		 *  5: Vol ren with ray tracing + density map
		 *  6: Vol ren with isosurface + density map
		 *  7: Vol ren with ray tracing + isosurface + density map
		 */
		void setRenderingMode(in long mode);

		/**
		 * Set the density transfer function.
		 */
		void setDenTransfer(in DenTransfer dtrans);

		/**
		 * Set the subvolume.
		 */
		void setSubVolume(in SubVolume vol);

	    //@}
	};

	/**
	 * Server Factory
	 */
	interface PVolManager {
	    /**@name methods */
	    //@{
		/**
		* create a new PVolServerSM instance and return the reference
		*/
		PVolServerSM connect();		
		//@}
	};
};
